app:
  instanceId: 00000

port:
  http:
    port: 8088
    session-timeout-in-minutes: 1
  websocket:
    session-timeout-in-minutes: 5


async:
  corePoolSize: 5
  maxPoolSize: 100
  queueCapacity: 100
  keepAliveSeconds: 60
  threadNamePrefix: Async-

scheduling:
  session:
    mdc-prefix: clrss
    corn: 0/100 * * * * *